"""Initial migration.

Revision ID: 664139c37514
Revises: 
Create Date: 2025-06-20 20:16:43.017940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664139c37514'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
